[1s1]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 80.00,0.00,56.57,56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,213,146
[1s2]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 56.57,56.57,0.00,80.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,235,146
[1s3]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 0.00,80.00,-56.57,56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,168
[1s4]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -56.57,56.57,-80.00,0.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,235
[1s5]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -80.00,0.00,-56.57,-56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,168,235
[1s6]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -56.57,-56.57,-0.00,-80.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,146,235
[1s7]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -0.00,-80.00,56.57,-56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,213
[1s8]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 56.57,-56.57,80.00,-0.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,146
[2s1]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 115.48,47.84,47.84,115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,213,146
[2s2]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 47.84,115.48,-47.84,115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,235,146
[2s3]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -47.84,115.48,-115.48,47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,168
[2s4]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -115.48,47.84,-115.48,-47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,235
[2s5]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -115.48,-47.84,-47.84,-115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,168,235
[2s6]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -47.84,-115.48,47.84,-115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,146,235
[2s7]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 47.84,-115.48,115.48,-47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,213
[2s8]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 115.48,-47.84,115.48,47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,146
[borders]
Meter=Shape
MeterStyle=StyleBorder
Shape=Ellipse 0,0,60.00 | Extend OffsetTransform,StyleAttributes
Shape2=Ellipse 0,0,100.00 | Extend OffsetTransform,StyleAttributes
Shape3=Ellipse 0,0,150.00 | Extend OffsetTransform,StyleAttributes
[Variables]
ButtonShift=150