[1s1]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 80.00,0.00,56.57,56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,213,146
[1s2]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 56.57,56.57,0.00,80.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,235,146
[1s3]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 0.00,80.00,-56.57,56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,168
[1s4]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -56.57,56.57,-80.00,0.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,235
[1s5]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -80.00,0.00,-56.57,-56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,168,235
[1s6]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -56.57,-56.57,-0.00,-80.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,146,235
[1s7]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -0.00,-80.00,56.57,-56.57,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,213
[1s8]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 56.57,-56.57,80.00,-0.00,80.00,80.00 | StrokeWidth 40.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,146
[2s1]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 115.48,47.84,47.84,115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,213,146
[2s2]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 47.84,115.48,-47.84,115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,235,146
[2s3]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -47.84,115.48,-115.48,47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,168
[2s4]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -115.48,47.84,-115.48,-47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,235,235
[2s5]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -115.48,-47.84,-47.84,-115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 146,168,235
[2s6]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc -47.84,-115.48,47.84,-115.48,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 191,146,235
[2s7]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 47.84,-115.48,115.48,-47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,213
[2s8]
Meter=Shape
MeterStyle=StyleButton
Shape=Arc 115.48,-47.84,115.48,47.84,125.00,125.00 | StrokeWidth 50.00 | Extend OffsetTransform,StyleAttributes
StyleAttributes=Stroke Color 235,146,146
[borders]
Meter=Shape
MeterStyle=StyleBorder
Shape=Ellipse 0,0,60.00 | Extend OffsetTransform,StyleAttributes
Shape2=Line 42.43,42.43,70.71,70.71 | Extend OffsetTransform,StyleAttributes
Shape3=Line 0.00,60.00,0.00,100.00 | Extend OffsetTransform,StyleAttributes
Shape4=Line -42.43,42.43,-70.71,70.71 | Extend OffsetTransform,StyleAttributes
Shape5=Line -60.00,0.00,-100.00,0.00 | Extend OffsetTransform,StyleAttributes
Shape6=Line -42.43,-42.43,-70.71,-70.71 | Extend OffsetTransform,StyleAttributes
Shape7=Line -0.00,-60.00,-0.00,-100.00 | Extend OffsetTransform,StyleAttributes
Shape8=Line 42.43,-42.43,70.71,-70.71 | Extend OffsetTransform,StyleAttributes
Shape9=Line 60.00,-0.00,100.00,-0.00 | Extend OffsetTransform,StyleAttributes
Shape10=Ellipse 0,0,100.00 | Extend OffsetTransform,StyleAttributes
Shape11=Line 38.27,92.39,57.40,138.58 | Extend OffsetTransform,StyleAttributes
Shape12=Line -38.27,92.39,-57.40,138.58 | Extend OffsetTransform,StyleAttributes
Shape13=Line -92.39,38.27,-138.58,57.40 | Extend OffsetTransform,StyleAttributes
Shape14=Line -92.39,-38.27,-138.58,-57.40 | Extend OffsetTransform,StyleAttributes
Shape15=Line -38.27,-92.39,-57.40,-138.58 | Extend OffsetTransform,StyleAttributes
Shape16=Line 38.27,-92.39,57.40,-138.58 | Extend OffsetTransform,StyleAttributes
Shape17=Line 92.39,-38.27,138.58,-57.40 | Extend OffsetTransform,StyleAttributes
Shape18=Line 92.39,38.27,138.58,57.40 | Extend OffsetTransform,StyleAttributes
Shape19=Ellipse 0,0,150.00 | Extend OffsetTransform,StyleAttributes
[Variables]
ButtonShift=150