[1s1]
Meter=Roundline
MeterStyle=Section
StartAngle=0.01
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=235,213,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s2]
Meter=Roundline
MeterStyle=Section
StartAngle=0.79539816339745
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=191,235,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s3]
Meter=Roundline
MeterStyle=Section
StartAngle=1.5807963267949
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=146,235,168
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s4]
Meter=Roundline
MeterStyle=Section
StartAngle=2.3661944901923
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=146,235,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s5]
Meter=Roundline
MeterStyle=Section
StartAngle=3.1515926535898
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=146,168,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s6]
Meter=Roundline
MeterStyle=Section
StartAngle=3.9369908169872
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=191,146,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s7]
Meter=Roundline
MeterStyle=Section
StartAngle=4.7223889803847
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=235,146,213
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[1s8]
Meter=Roundline
MeterStyle=Section
StartAngle=5.5077871437821
RotationAngle=0.76539816339745
LineStart=60
LineLength=100
HoverColor=235,146,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s1]
Meter=Roundline
MeterStyle=Section
StartAngle=0.39927802906715
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=235,213,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s2]
Meter=Roundline
MeterStyle=Section
StartAngle=1.1846761924646
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=191,235,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s3]
Meter=Roundline
MeterStyle=Section
StartAngle=1.970074355862
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=146,235,168
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s4]
Meter=Roundline
MeterStyle=Section
StartAngle=2.7554725192595
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=146,235,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s5]
Meter=Roundline
MeterStyle=Section
StartAngle=3.5408706826569
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=146,168,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s6]
Meter=Roundline
MeterStyle=Section
StartAngle=4.3262688460544
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=191,146,235
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s7]
Meter=Roundline
MeterStyle=Section
StartAngle=5.1116670094518
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=235,146,213
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[2s8]
Meter=Roundline
MeterStyle=Section
StartAngle=5.8970651728493
RotationAngle=0.77224026866061
LineStart=102
LineLength=152
HoverColor=235,146,146
OverAction=[!CommandMeasure "Lua" "onHover('#CURRENTSECTION#')"]
LeaveAction=[!CommandMeasure "Lua" "onLeave('#CURRENTSECTION#')"]
ClickAction=[!CommandMeasure "Lua" "onClick('#CURRENTSECTION#')"]
[cb0]
Meter=Roundline
MeterStyle=Section|CircleBorder
LineStart=60
LineLength=62
[cb1]
Meter=Roundline
MeterStyle=Section|CircleBorder
LineStart=100
LineLength=102
[b1_1]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=0
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_2]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=0.78539816339745
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_3]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=1.5707963267949
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_4]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=2.3561944901923
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_5]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=3.1415926535898
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_6]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=3.9269908169872
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_7]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=4.7123889803847
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[b1_8]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=5.4977871437821
RotationAngle=0.78539816339745
LineStart=60
LineLength=100
LineWidth=2
[cb2]
Meter=Roundline
MeterStyle=Section|CircleBorder
LineStart=152
LineLength=154
[b2_1]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=0.39269908169872
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_2]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=1.1780972450962
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_3]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=1.9634954084936
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_4]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=2.7488935718911
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_5]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=3.5342917352885
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_6]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=4.319689898686
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_7]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=5.1050880620834
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[b2_8]
Meter=Roundline
MeterStyle=Section|LineBorder
StartAngle=5.8904862254809
RotationAngle=0.78539816339745
LineStart=102
LineLength=152
LineWidth=2
[Variables]
Size=312