[Variables]
BorderColor=255,255,255

RingCount=2
RingCenterSize=60

Ring1.Count=8
Ring1.Size=40

Ring2.Count=8
Ring2.Size=50
Ring2.Offset=(#2PI#/16)

; Syntax: [Ring#]s[Section#][Option]
; Valid options are Bang, Image and Color
; Hover over a section on the skin and it'll tell you what that section is named

; For more information on the Bang option, see https://docs.rainmeter.net/manual/bangs/
; For more Information on the Color option, see https://docs.rainmeter.net/manual/skins/option-types/#Color
1s1Bang=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
1s1Image=chrome.png
1s1Color=76,139,245

1s2Bang=["C:\Program Files (x86)\Mozilla Firefox\firefox.exe"]
1s2Image=firefox.png
1s2Color=240,150,96

